agi fort77
agi gfortran
agi libbz2-dev
agi libcurl4-openssl-dev
agi liblzma-dev
agi libpcre3
agi libpcre3-dev
agi libssl-dev
agi libudunits2-dev
agi libxml2-dev
agi libzmq5
agi libzmq5-dev
agi texinfo
agi texlive
agi texlive-fonts-extra
agi xorg-dev
agi zlib1g-dev
