install.packages("abind")
install.packages("batchtools")
install.packages("bindr")
install.packages("BiocManager")
install.packages("Cairo")
install.packages("clustermq")
BiocManager::install("CodeDepends")
# source("https://bioconductor.org/biocLite.R")
# biocLite("graph", ask = FALSE, suppressUpdates = TRUE)
# install.packages("CodeDepends")
install.packages("covr")
install.packages("devtools")
install.packages("downloader")
install.packages("drake")
install.packages("future")
install.packages("future.apply")
install.packages("future.batchtools")
install.packages("ggraph")
install.packages("goodpractice")
install.packages("hunspell")
install.packages("knitr")
install.packages("lintr")
install.packages("lubridate")
install.packages("networkD3")
install.packages("prettycode")
install.packages("profile")
install.packages("profvis")
install.packages("reprex")
install.packages("rmarkdown")
install.packages("roxygen2")
install.packages("spelling")
install.packages("styler")
install.packages("testthat")
install.packages("tidyverse")
install.packages("txtq")
install.packages("visNetwork")
install.packages("webshot")
webshot::install_phantomjs()
