Rscript \
  -e 'install.packages("abind")' \
  -e 'install.packages("batchtools")' \
  -e 'install.packages("BiocManager")' \
  -e 'install.packages("clustermq")' \
  -e 'BiocManager::install("CodeDepends")' \
  -e 'install.packages("covr")' \
  -e 'install.packages("devtools")' \
  -e 'install.packages("drake")' \
  -e 'install.packages("future")' \
  -e 'install.packages("future.apply")' \
  -e 'install.packages("future.batchtools")' \
  -e 'install.packages("ggraph")' \
  -e 'install.packages("goodpractice")' \
  -e 'install.packages("hunspell")' \
  -e 'install.packages("lintr")' \
  -e 'install.packages("networkD3")' \
  -e 'install.packages("prettycode")' \
  -e 'install.packages("reprex")' \
  -e 'install.packages("roxygen2")' \
  -e 'install.packages("spelling")' \
  -e 'install.packages("styler")' \
  -e 'install.packages("testthat")' \
  -e 'install.packages("tidyverse")' \
  -e 'install.packages("txtq")' \
  -e 'install.packages("visNetwork")' \
  -e 'install.packages("webshot")' \
  -e 'webshot::install_phantomjs'
